#nw_user_newuser:
#    pattern:  /asignarRoles
#    defaults: { _controller: NWUserBundle:User:asignarRoles }

nw_user_registronovios:
    pattern:  /registronovios
    defaults: { _controller: NWUserBundle:User:registronovios }

nw_user_loginnovios:
    pattern:  /loginnovios
    defaults: { _controller: NWUserBundle:User:loginnovios }

nw_user_registroproveedores:
    pattern:  /registroproveedores
    defaults: { _controller: NWUserBundle:User:registroproveedores }

nw_user_registroreportero:
    pattern:  /registroreportero
    defaults: { _controller: NWUserBundle:User:registroReportero }

nw_user_registro_exitoso:
    pattern:  /registroexitoso
    defaults: { _controller: NWUserBundle:User:registroExitoso }