nw_user_newuser:
    pattern:  /asignarRoles
    defaults: { _controller: NWUserBundle:User:asignarRoles }

nw_user_registronovios:
    pattern:  /registronovios
    defaults: { _controller: NWUserBundle:User:registronovios }

nw_user_pruebaRegistro:
    pattern:  /prueba
    defaults: { _controller: NWUserBundle:User:pruebaRegistro }