# src/NW/UserBundle/Resources/config/doctrine/Estados.orm.yml
NW\UserBundle\Entity\Estados:
    type: entity
    table: estados
    manyToOne:
        pais:
            targetEntity: Paises
            inversedBy: Estados
            joinColumn:
                name: paisId
                referencedColumnName: id
    oneToMany:
        registronovios:
            targetEntity: registronovios
            mappedBy: Estados 
    oneToMany:
        registroproveedores:
            targetEntity: registroproveedores
            mappedBy: Estados 
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        paisId:
            type: integer
        estado:
            type: string
            length: 100