# src/NW/UserBundle/Resources/config/doctrine/registroproveedores.orm.yml
NW\UserBundle\Entity\registroproveedores:
    type:  entity
    table: proveedores
    oneToOne:
        user:
            targetEntity: User
            inversedBy: registroproveedores
            joinColumn:
                name: usuarioId
                referencedColumnName: id
        codigoVendedor:
            targetEntity: NW\PrincipalBundle\Entity\Codigos
            mappedBy: vendedor
    manyToOne:
        estados:
            targetEntity: NW\PrincipalBundle\Entity\Estados
            inversedBy: registroproveedores
            joinColumn:
                name: estado
                referencedColumnName: id
    oneToMany:
        galeria:
            targetEntity: NW\PrincipalBundle\Entity\GaleriaProveedor
            mappedBy: proveedor
        resenas:
            targetEntity: NW\PrincipalBundle\Entity\Resena
            mappedBy: proveedor
        codigos:
            targetEntity: NW\PrincipalBundle\Entity\Codigos
            mappedBy: proveedor
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        usuarioId:
            type: integer
        tipoPersona:
            type: string
            length: 100
        nombreRazon:
            type: string
            length: 100
        apellidoPaterno:
            type: string
            length: 100
        apellidoMaterno:
            type: string
            length: 100
        rfc:
            type: string
            length: 100
        email:
            type: string
            length: 100
        lada:
            type: string
            length: 100
        telefono:
            type: string
            length: 100
        celular:
            type: string
            length: 100
        direccion:
            type: string
            length: 100
        estado:
            type: integer
        ciudad:
            type: string
            length: 100
        cp:
            type: string
            length: 100
        plan:
            type: string
            length: 100
        path:
            type: string
            length: 255
            nullable: true
            default: NULL
            columnDefinition: VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL
        nombreComercial:
            type: string
            length: 255
            nullable: true
            default: NULL
            columnDefinition: VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL
        descripcion:
            type: string
            length: 255
            nullable: true
            default: NULL
            columnDefinition: VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL