# src/NW/UserBundle/Resources/config/doctrine/registronovios.orm.yml
NW\UserBundle\Entity\registronovios:
    type:  entity
    table: novios
    oneToOne:
        user:
            targetEntity: User
            inversedBy: registronovios
            joinColumn:
                name: usuarioId
                referencedColumnName: id
    manyToOne:
        estados:
            targetEntity: NW\PrincipalBundle\Entity\Estados
            inversedBy: registronovios
            joinColumn:
                name: noviaEstado
                referencedColumnName: id
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        usuarioId:
            type: integer
        noviaNombre:
            type: string
            length: 100
        noviaSNombre:
            type: string
            length: 100
        noviaAPaterno:
            type: string
            length: 100
        noviaAMaterno:
            type: string
            length: 100
        noviaEMail:
            type: string
            length: 100
        noviaLada:
            type: string
            length: 100
        noviaTelefono:
            type: string
            length: 100
        noviaCelular:
            type: string
            length: 100
        noviaDireccion:
            type: string
            length: 100
        noviaEstado:
            type: integer
        noviaCiudad:
            type: string
            length: 100
        noviaCP:
            type: string
            length: 100
        novioNombre:
            type: string
            length: 100
        novioSNombre:
            type: string
            length: 100
        novioAPaterno:
            type: string
            length: 100
        novioAMaterno:
            type: string
            length: 100
        novioEMail:
            type: string
            length: 100
        novioLada:
            type: string
            length: 100
        novioTelefono:
            type: string
            length: 100
        novioCelular:
            type: string
            length: 100
        novioDireccion:
            type: string
            length: 100
        novioEstado:
            type: integer
        novioCiudad:
            type: string
            length: 100
        novioCP:
            type: string
            length: 100