# src/NW/UserBundle/Resources/config/doctrine/User.orm.yml
NW\UserBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToOne:
        novios:
            targetEntity: Novios
            mappedBy: User
    oneToOne:
        novias:
            targetEntity: Novias
            mappedBy: User
    oneToOne:
        registroproveedores:
            targetEntity: registroproveedores
            mappedBy: User