# src/NW/UserBundle/Resources/config/doctrine/User.orm.yml
NW\UserBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToOne:
        novios:
            targetEntity: Novios
            mappedBy: user
        novias:
            targetEntity: Novias
            mappedBy: user
        registroproveedores:
            targetEntity: registroproveedores
            mappedBy: user
        anuncios:
            targetEntity:  NW\PrincipalBundle\Entity\Anuncios
            mappedBy: user
    oneToMany:
        checklist:
            targetEntity:  NW\PrincipalBundle\Entity\Checklist
            mappedBy: user
        listainvitados:
            targetEntity:  NW\PrincipalBundle\Entity\ListaInvitados
            mappedBy: user
        bodas:
            targetEntity:  NW\PrincipalBundle\Entity\Bodas
            mappedBy: user
        padrinos:
            targetEntity:  NW\PrincipalBundle\Entity\Padrinos
            mappedBy: user
        notas:
            targetEntity:  NW\PrincipalBundle\Entity\Notas
            mappedBy: user
        mesaregalos:
            targetEntity:  NW\PrincipalBundle\Entity\MesaRegalos
            mappedBy: user
        articulos:
            targetEntity:  NW\PrincipalBundle\Entity\Articulos
            mappedBy: user