# src/NW/PrincipalBundle/Resources/config/doctrine/Anuncios.orm.yml
NW\PrincipalBundle\Entity\Anuncios:
    type: entity
    table: anuncios
    oneToOne:
        user:
            targetEntity: NW\UserBundle\Entity\User
            inversedBy: anuncios
            joinColumn:
                name: usuarioId
                referencedColumnName: id
    id:
        id:
            type: integer
            generator:
                strategy: AUTO	
    fields:
        usuarioId:
            type: integer
        webpage:
            type: string   
            length: 255
        path:
            type: string
            length: 255