# src/NW/PrincipalBundle/Resources/config/doctrine/Articulos.orm.yml
NW\PrincipalBundle\Entity\Articulos:
    type: entity
    table: articulos
    manyToOne:
        user:
            targetEntity: NW\UserBundle\Entity\User
            inversedBy: articulos
            joinColumn:
                name: usuarioId
                referencedColumnName: id
        categoria:
            targetEntity: Categorias
            inversedBy: articulo
            joinColumn:
                name: categoriaId
                referencedColumnName: id
    oneToMany:
        fotosarticulos:
            targetEntity: FotosArticulos
            mappedBy: articulo
    oneToOne:
        banner:
            targetEntity: Banners
            mappedBy: articulo
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        usuarioId:
            type: integer
        idInterno:
            type: string
        categoriaId:
            type: integer
        nombre:
            type: string
            length: 100
        descripcion:
            type: text
        stock:
            type: integer
        precio:
            type: integer
        precioPromocion:
            type: integer
        tamanos:
            type: simple_array
        tipo:
            type: string
            length: 15
        estatus:
            type: boolean