# src/NW/PrincipalBundle/Resources/config/doctrine/Bodas.orm.yml
NW\PrincipalBundle\Entity\Bodas:
    type: entity 
    table: bodas
    manyToOne:
        user:
            targetEntity: NW\UserBundle\Entity\User
            inversedBy: bodas
            joinColumn:
                name: usuarioId
                referencedColumnName: id
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        usuarioId:
            type: integer
        ceremonia:
            type: string
            length: 100
        ceremonia_direccion:
            type: string
            length: 200
            nullable: true
        recepcion:
            type: string
            length: 100
        recepcion_direccion:
            type: string
            length: 200
            nullable: true
        fecha_boda:
            type: datetime