# src/NW/PrincipalBundle/Resources/config/doctrine/CategoriaCalendario.orm.yml
NW\PrincipalBundle\Entity\CategoriaCalendario:
    type: entity
    table: NWCategoriasCalendario
    oneToMany:
        tareas:
            targetEntity: TareaCalendario
            inversedBy: tareasCalendario
            mappedBy: categoria
    id:
        id:
            type: integer
            generator:
                strategy: AUTO	
    fields:
        categoria:
            type: string
            length: 150