# src/NW/PrincipalBundle/Resources/config/doctrine/Estados.orm.yml
NW\PrincipalBundle\Entity\Estados:
    type: entity
    table: estados
    manyToOne:
        pais:
            targetEntity: Paises
            inversedBy: estados
            joinColumn:
                name: paisId
                referencedColumnName: id
    oneToMany:
        novios:
            targetEntity: NW\UserBundle\Entity\Novios
            mappedBy: estados
        novias:
            targetEntity: NW\UserBundle\Entity\Novias
            mappedBy: estados
        registroproveedores:
            targetEntity: NW\UserBundle\Entity\registroproveedores
            mappedBy: estados
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        paisId:
            type: integer
        estado:
            type: string
            length: 100