# src/NW/PrincipalBundle/Resources/config/doctrine/FotosArtic.orm.yml
NW\PrincipalBundle\Entity\FotosArtic.orm.yml:
    type: entity
    table: fotosartic
    manyToOne:
        articulos:
            targetEntity: NW\PrincipalBundle\Entity\Articulos
            inversedBy: fotosartic
            joinColumn:
                name: articuloId
                referencedColumnName: id
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        articuloId:
            type: integer
        path:
            type: string
            length: 255