# src/NW/PrincipalBundle/Resources/config/doctrine/Notas.orm.yml
NW\PrincipalBundle\Entity\Notas:
    type: entity 
    table: notas
    manyToOne:
        user:
            targetEntity: NW\UserBundle\Entity\User
            inversedBy: Notas
            joinColumn:
                name: usuarioId
                referencedColumnName: id
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        usuarioId:
            type: integer
        titulo:
            type: string
            length: 100
        descripcion:
            type: text