# src/NW/PrincipalBundle/Resources/config/doctrine/Padrinos.orm.yml
NW\PrincipalBundle\Entity\Padrinos:
    type: entity 
    table: padrinos 
    manyToOne:
        user:
            targetEntity: NW\UserBundle\Entity\User
            inversedBy: Padrinos
            joinColumn:
                name: usuarioId
                referencedColumnName: id
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        usuarioId:
            type: integer
        padrino:
            type: string
            length: 100
        categoria:
            type: string
            length: 100