# src/NW/PrincipalBundle/Resources/config/doctrine/Uploads.orm.yml
NW\PrincipalBundle\Entity\Uploads:
    type: entity
    table: uploads 
    id:
        id:
            type: integer
            generator:
                strategy: AUTO	
    fields:
        name:
            type: string   
            length: 255
        path:
            type: string
            length: 255