parameters:
    database_driver: pdo_mysql
    database_host: sql3.freemysqlhosting.net
    database_port: 3306
    database_name: sql339538
    database_user: sql339538
    database_password: gW6%%bU8%%
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: es
    secret: ThisTokenIsNotSoSecretChangeIt