parameters:
    paypal.express_checkout.username: 'docserchek-facilitator_api1.gmail.com'
    paypal.express_checkout.password: '32CEGRDF5J9EM2WS'
    paypal.express_checkout.signature: 'AFcWxV21C7fd0v3bYYYRCpSSRl31A7GLJfxDJ2SFxVMqGhE7iJkP3sYA'
    paypal.express_checkout.usd_testuser_login: 'docserchek-buyer@gmail.com'
    paypal.express_checkout.usd_testuser_password: '12345678'

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    payum:
                        is_bundle: false
                        type: xml
                        dir: %kernel.root_dir%/../vendor/payum/core/Payum/Core/Bridge/Doctrine/Resources/mapping
                        prefix: Payum\Core\Model

payum:
    security:
        token_storage:
            NW\PaymentBundle\Entity\PaymentSecurityToken:
                doctrine: orm

    storages:
        NW\PaymentBundle\Entity\PaymentDetails:
            payment:
                all: true
            doctrine: orm

    contexts:
        paypal_express_checkout_and_doctrine_orm:
            paypal_express_checkout_nvp:
                username: '%paypal.express_checkout.username%'
                password: '%paypal.express_checkout.password%'
                signature: '%paypal.express_checkout.signature%'
                sandbox: true