# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_PROVEEDOR_ANUNCIO: ROLE_PROVEEDOR
        ROLE_PROVEEDOR_BASICO: ROLE_PROVEEDOR
        ROLE_PROVEEDOR_ESTANDAR: [ROLE_PROVEEDOR_BASICO, ROLE_PROVEEDOR_ANUNCIO]
        ROLE_PROVEEDOR_PLUS: ROLE_PROVEEDOR_ESTANDAR
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_NOVIO, ROLE_REPORTERO, ROLE_PROVEEDOR_PLUS]

    providers:
            fos_userbundle:
                id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registro$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/proveedores/, role: ROLE_PROVEEDOR }
        - { path: ^/novios/, role: ROLE_NOVIO }
        - { path: ^/reporteros/, role: ROLE_REPORTERO }