# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_PROVEEDOR_ANUNCIO: ROLE_PROVEEDOR
        ROLE_PROVEEDOR_BASICO: ROLE_PROVEEDOR
        ROLE_PROVEEDOR_ESTANDAR: [ROLE_PROVEEDOR_BASICO, ROLE_PROVEEDOR_ANUNCIO]
        ROLE_PROVEEDOR_PLUS: ROLE_PROVEEDOR_ESTANDAR
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_NOVIO, ROLE_REPORTERO, ROLE_PROVEEDOR_PLUS]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        secure_area:
            pattern: ^/

            oauth:
                failure_path: /connect
                login_path: /connect
                check_path: /connect
                provider: fos_userbundle
                resource_owners:
                    facebook: "/login/check-facebook"
                oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge

            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path: /login_check
                login_path: /login
                default_target_path: / #default location to redirect after successful login

            anonymous: true
            logout: true

    access_control:
        - { path: ^/secure_area/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secure_area/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secure_area/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secure_area/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secure_area/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secure_area, roles: ROLE_USER }
        #...
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registro$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/admin$, roles: ROLE_ADMIN }
        - { path: ^/proveedores/, role: ROLE_PROVEEDOR }
        - { path: ^/novios/, role: ROLE_NOVIO }
        - { path: ^/reporteros/, role: ROLE_REPORTERO }