# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_PROVEEDOR_ANUNCIO: ROLE_PROVEEDOR
        ROLE_PROVEEDOR_BASICO: ROLE_PROVEEDOR
        ROLE_PROVEEDOR_ESTANDAR: [ROLE_PROVEEDOR_BASICO, ROLE_PROVEEDOR_ANUNCIO]
        ROLE_PROVEEDOR_PLUS: ROLE_PROVEEDOR_ESTANDAR
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_NOVIO, ROLE_REPORTERO, ROLE_PROVEEDOR_PLUS]

    providers:
            fos_userbundle:
                id: fos_user.user_provider.username

    firewalls:
        secure_area:
            pattern: ^/
            oauth:
                failure_path: /secure_area/connect
                login_path: /secure_area/connect
                check_path: /secure_area/connect
                provider: fos_userbundle
                resource_owners:
                    facebook:           "/secure_area/login/check-facebook"
                oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge
            anonymous:    true
            #logout:
            #    path:           /secure_area/logout
            #    target:         /secure_area/connect

            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registro$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/admin$, roles: ROLE_ADMIN }
        - { path: ^/proveedores/, role: ROLE_PROVEEDOR }
        - { path: ^/novios/, role: ROLE_NOVIO }
        - { path: ^/reporteros/, role: ROLE_REPORTERO }
        #...
        - { path: ^/secure_area/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secure_area/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secure_area, roles: ROLE_USER }