parameters:
#    nw_security.example.class: NW\SecurityBundle\Example

services:
#    nw_security.example:
#        class: %nw_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
