parameters:
#    nw_principal.example.class: NW\PrincipalBundle\Example

services:
#    nw_principal.example:
#        class: %nw_principal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
