#parameters:
#    nw_principal.controller.forms.class: NW\PrincipalBundle\Controller\FormsController
#services:
#    nw_principal.forms.controller:
#        class: "%nw_principal.controller.forms.class%"
services:
    nw_principal.forms.controller.manyForms:
        class: NW\PrincipalBundle\Controller\FormsController\manyFormsAction